### ISSUE TITLE
No more firmware_install if building with Kernel 4.14

### ISSUE THREAD

**Issue by boltronics** [michaelfranzl/rpi23-gen-image#14] opened 2018-05-19 09:38 UTC
It looks like this fork has hit the same issue as the original project:
https://github.com/drtyhlpr/rpi23-gen-image/issues/120

The latest kernels are crashing with the following:
```
  INSTALL net/rfkill/rfkill.ko
  INSTALL net/tls/tls.ko
  INSTALL net/wireless/cfg80211.ko
  INSTALL sound/soc/bcm/snd-soc-bcm2835-i2s.ko
  DEPMOD  4.16.9
make: Leaving directory '/home/user/workspace/rpi23-gen-image/images/stretch/build/chroot/usr/src/linux'
+ make -C /home/user/workspace/rpi23-gen-image/images/stretch/build/chroot/usr/src/linux ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_FW_PATH=../../../lib firmware_install
make: Entering directory '/home/user/workspace/rpi23-gen-image/images/stretch/build/chroot/usr/src/linux'
make: *** No rule to make target 'firmware_install'.  Stop.
make: Leaving directory '/home/user/workspace/rpi23-gen-image/images/stretch/build/chroot/usr/src/linux'
+ cleanup
+ set +x
killing processes using mount point ...
removing temporary mount points ...
root@buildbox:/home/user/workspace/rpi23-gen-image# 
```

**Comment by boltronics** [comment] 2018-05-19 09:44
It looks like this is only called if `ENABLE_REDUCE` is set to `true`. I'm guessing that's a secondary issue with that particular `if` condition.

**Comment by Lesik** [comment] 2018-05-27 18:50
I need to append that this appears to be unrelated to `ENABLE_REDUCE`, as I am facing the same issue despite having it set to `false`.

I am unsure about the solution proposed in https://github.com/drtyhlpr/rpi23-gen-image/issues/120 to just remove the `firmware_install`, as the resulting image fails to boot on my Raspberry Pi 3 (possibly due to missing `/boot/kernel.img` as the LED flashed seven times?).

**Comment by michaelfranzl** [comment] 2018-05-27 20:53
This is weird, because just two weeks ago I successfully built with the updated kernel version given in the README:

> 625e2001e99e82ea3eb5b0370a428a4328b9166b (May 2018, approx. version 4.17)

**Comment by boltronics** [comment] 2018-05-27 21:55
From [bootstrap.d/13-kernel.sh](https://github.com/michaelfranzl/rpi23-gen-image/blob/5c41b2d987b53b87cb979876a531c1543d89129b/bootstrap.d/13-kernel.sh):

```
# Install kernel modules
if [ "$ENABLE_REDUCE" = true ] ; then
  make -C "${KERNEL_DIR}" ARCH="${KERNEL_ARCH}" CROSS_COMPILE="${CROSS_COMPILE}" INSTALL_MOD_STRIP=1 INSTALL_MOD_PATH=../../.. modules_install
  
else
  make -C "${KERNEL_DIR}" ARCH="${KERNEL_ARCH}" CROSS_COMPILE="${CROSS_COMPILE}" INSTALL_MOD_PATH=../../.. modules_install

  # Install kernel firmware
  make -C "${KERNEL_DIR}" ARCH="${KERNEL_ARCH}" CROSS_COMPILE="${CROSS_COMPILE}" INSTALL_FW_PATH=../../../lib firmware_install
fi
```

@Lesik What I meant to say was that this only occurs if `ENABLE_REDUCE` is _not_ set to `true`. @michaelfranzl Just from reading the above code snippet, there's no way you built that kernel with the option enabled.

I don't know why the kernel firmware lines are in the `if` block at all, but if it was, everyone building a modern kernel would be having an issue. As it stands, it looks like some firmware might be missing from all builds in the last couple of years where they were created with `ENABLE_REDUCE` set to `true`, which would be really strange to not have been detected in all this time. Maybe most Pi models can get by without it?

When I filed this report, I was trying to get a Pi3+ working (the only Pi model I have), and was running into all kinds of issues. Random crashes, Ethernet not detected, no audio hardware detected (`ENABLE_SOUND` didn't help), etc. I'm not sure, but perhaps this was part of the reason. I am quite sure that 4.10 doesn't work at least, despite what the README.md says.

**Comment by michaelfranzl** [comment] 2018-05-28 11:04
I built with `ENABLE_REDUCE=true`, so that explains why my build was successful. It seems that `firmware_install` is not necessary since all hardware components are still detected (with the exception of the onboard LEDs on a RPi3).

I'm thinking about removing the `ENABLE_REDUCE` option entirely. It could be replaced with custom scripts removing unnecessary files from the staging directory before it is copied to a SD card.

**Comment by Lesik** [comment] 2018-05-28 17:38
My suspicion that the missing `/boot/kernel.img` is critical for the boot process seems correct. I just tried the image on a Raspberry Pi 3, and it doesn't boot for the file was not found.

Can somebody confirm this being related to `firmware_install` or is this a different issue entirely?

**Comment by michaelfranzl** [comment] 2018-05-28 19:08
I just removed the making of the `firmware_install` target when `ENABLE_REDUCE=false`. I actually have always used `ENABLE_REDUCE=true`, which never installed firmware, and my Raspberrys worked just fine without the firmware.

@Lesik: `kernel.img` is and has never been used in this project. You need the following files in the boot partition (for a RPi3):

`bcm2837-rpi-3-b.dtb  boot.scr     config.txt    fixup.dat    linux.uImage  start.elf    u-boot.bin  bootcode.bin         cmdline.txt  fixup_cd.dat  fixup_x.dat  start_cd.elf  start_x.elf  uboot.mkimage`

**Comment by Lesik** [comment] 2018-05-28 20:21
@michaelfranzl Those files are present, but the Raspberry Pi 3 still refuses to boot. Should I open a separate issue for that? It's just that the script worked great when I last tried with the previous (Feb 2017) kernel commit, hence my suspicion of it being related to `firmware_install`.

**Comment by michaelfranzl** [comment] 2018-05-28 21:20
@Lesik: The files are in the boot partition, mounted at /boot/firmware. What you're seeing is a separate issue. It may come from the newer "confirmed" kernel version 625e2001 (4.17) which I had put into the README on May 5th. However, it seems I did not test properly back then. I just rebuilt, and the RPi3 wouldn't boot any more. Unfortunately, I have no time to investigate this further, so I simply put back the older working kernel version 60e8d3e1 (4.10) into the README and the corresponding config files `working_*.txt`.

As for the `firmware_install` issue at hand, `firmware_install` was never necessary for the operation of the RPis, so above linked commit will at least guarantee that running the script will succeed even with newer kernels. Thus I'm closing this issue.

However, if newer kernels will boot is an entirely different question. For now, everyone please use the exact kernel commit ID given in the README, plus the corresponding config files `working_*.txt`.

**Closed as completed by michaelfranzl** 2018-05-28 21:20 UTC

**Comment by boltronics** [comment] 2018-05-28 23:46
@michaelfranzl Is 4.10 supposed to work with the Pi 3+? It's been a couple of weeks since I tried, but I had much more luck with 4.17 (although still buggy enough to be impractical for general use).

Edit: 4.17 was built with the `firmware_install` argument deleted when I tried.

**Comment by michaelfranzl** [comment] 2018-05-29 07:06
@boltronics Yes, 4.10 works onthe Pi3.

**Comment by boltronics** [comment] 2018-05-29 07:19
3+ not 3. As I understand the Ethernet setup is different for example - something I had problems getting to work.

**Comment by michaelfranzl** [comment] 2018-05-29 09:28
To be more specific, 4.10 works for version 3 board revision B V1.2. I just made a change to the README to be more explicit about versions.
